services:
  postgres:
    image: postgres:latest
    container_name: postgres_springboot_agregador_investimentos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bancodeestudoscrud
      POSTGRES_DB: agregadorinvestimentos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: